// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        ArticleList: typeof import('./src/components/card/ArticleCardIndex.vue')['default'];
        CollectionLink: typeof import('./src/components/index/articleList/CollectionLink.vue')['default'];
        CommentsLink: typeof import('./src/components/index/articleList/CommentsLink.vue')['default'];
        ElButton: typeof import('element-plus/es')['ElButton'];
        ElDropdown: typeof import('element-plus/es')['ElDropdown'];
        ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem'];
        ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu'];
        ElIcon: typeof import('element-plus/es')['ElIcon'];
        Footer: typeof import('./src/components/nav/Footer.vue')['default'];
        Header: typeof import('./src/components/nav/Header.vue')['default'];
        LikeBtn: typeof import('./src/components/index/articleList/LikeBtn.vue')['default'];
        RouterLink: typeof import('vue-router')['RouterLink'];
        RouterView: typeof import('vue-router')['RouterView'];
        ShareLink: typeof import('./src/components/index/articleList/ShareLink.vue')['default'];
        SortBy: typeof import('./src/components/nav/SortBy.vue')['default'];
    }
}
