/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        AllTypePreviewList: typeof import('./components/common/AllTypePreviewList.vue')['default'];
        AnswerQuestionForm: typeof import('./components/dialog/AnswerQuestionForm.vue')['default'];
        ArticleOptionMenu: typeof import('./components/menu/ArticleOptionMenu.vue')['default'];
        AskQuestionForm: typeof import('./components/dialog/AskQuestionForm.vue')['default'];
        CollectionLink: typeof import('./components/index/articleList/CollectionLink.vue')['default'];
        Comment: typeof import('./components/comments/Comment.vue')['default'];
        CommentForm: typeof import('./components/dialog/CommentForm.vue')['default'];
        CommentsLink: typeof import('./components/index/articleList/CommentsLink.vue')['default'];
        EditArticleForm: typeof import('./components/dialog/EditArticleForm.vue')['default'];
        ElAffix: typeof import('element-plus/es')['ElAffix'];
        ElAvatar: typeof import('element-plus/es')['ElAvatar'];
        ElBacktop: typeof import('element-plus/es')['ElBacktop'];
        ElButton: typeof import('element-plus/es')['ElButton'];
        ElDivider: typeof import('element-plus/es')['ElDivider'];
        ElDropdown: typeof import('element-plus/es')['ElDropdown'];
        ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem'];
        ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu'];
        ElIcon: typeof import('element-plus/es')['ElIcon'];
        ElMenu: typeof import('element-plus/es')['ElMenu'];
        ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
        ElProgress: typeof import('element-plus/es')['ElProgress'];
        ElTag: typeof import('element-plus/es')['ElTag'];
        ElTooltip: typeof import('element-plus/es')['ElTooltip'];
        FilterBy: typeof import('./components/nav/FilterBy.vue')['default'];
        Footer: typeof import('./components/nav/Footer.vue')['default'];
        Header: typeof import('./components/nav/Header.vue')['default'];
        IAntDesignClockCircleFilled: typeof import('~icons/ant-design/clock-circle-filled')['default'];
        IAntDesignEyeOutlined: typeof import('~icons/ant-design/eye-outlined')['default'];
        IAntDesignUnorderedListOutlined: typeof import('~icons/ant-design/unordered-list-outlined')['default'];
        ILogosElement: typeof import('~icons/logos/element')['default'];
        ILogosMysql: typeof import('~icons/logos/mysql')['default'];
        ILogosRedis: typeof import('~icons/logos/redis')['default'];
        ILogosSpringIcon: typeof import('~icons/logos/spring-icon')['default'];
        ILogosTailwindcssIcon: typeof import('~icons/logos/tailwindcss-icon')['default'];
        ILogosTypescriptIcon: typeof import('~icons/logos/typescript-icon')['default'];
        ILogosVitejs: typeof import('~icons/logos/vitejs')['default'];
        ILogosVue: typeof import('~icons/logos/vue')['default'];
        IMdiEye: typeof import('~icons/mdi/eye')['default'];
        IMdiThumbUp: typeof import('~icons/mdi/thumb-up')['default'];
        LikeBtn: typeof import('./components/index/articleList/LikeBtn.vue')['default'];
        Loading: typeof import('./components/others/Loading.vue')['default'];
        LoginForm: typeof import('./components/dialog/LoginForm.vue')['default'];
        NoResult: typeof import('./components/others/NoResult.vue')['default'];
        OptionMenu: typeof import('./components/aside/OptionMenu.vue')['default'];
        Pagination: typeof import('./components/index/articleList/Pagination.vue')['default'];
        PublishArticleForm: typeof import('./components/dialog/PublishArticleForm.vue')['default'];
        RouterLink: typeof import('vue-router')['RouterLink'];
        RouterView: typeof import('vue-router')['RouterView'];
        SendPostForm: typeof import('./components/dialog/SendPostForm.vue')['default'];
        ShareLink: typeof import('./components/index/articleList/ShareLink.vue')['default'];
        SortBy: typeof import('./components/nav/SortBy.vue')['default'];
        SubscribeBtn: typeof import('./components/others/SubscribeBtn.vue')['default'];
        UploadVideoForm: typeof import('./components/dialog/UploadVideoForm.vue')['default'];
        UserInfo: typeof import('./components/aside/UserInfo.vue')['default'];
        UserInfoLite: typeof import('./components/aside/UserInfoLite.vue')['default'];
        UserLikedAnswerList: typeof import('./components/user/UserLikedAnswerList.vue')['default'];
        UserProfile: typeof import('./components/user/UserProfile.vue')['default'];
        UsersComment: typeof import('./components/comments/UsersComment.vue')['default'];
        WelcomeCard: typeof import('./components/index/welcome/WelcomeCard.vue')['default'];
    }
}
