// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleList: typeof import('./components/index/ArticleList.vue')['default']
    CollectionLink: typeof import('./components/index/articleList/CollectionLink.vue')['default']
    CommentsLink: typeof import('./components/index/articleList/CommentsLink.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Footer: typeof import('./components/index/nav/Footer.vue')['default']
    Header: typeof import('./components/index/nav/Header.vue')['default']
    IEpAim: typeof import('~icons/ep/aim')['default']
    IEpExpand: typeof import('~icons/ep/expand')['default']
    IEpIcon: typeof import('~icons/ep/icon')['default']
    LikeBtn: typeof import('./components/index/articleList/LikeBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareLink: typeof import('./components/index/articleList/ShareLink.vue')['default']
    SortBy: typeof import('./components/index/nav/SortBy.vue')['default']
  }
}
